// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: meshservice.proto

package meshservice

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type JoinResponse_Result int32

const (
	JoinResponse_OK    JoinResponse_Result = 0
	JoinResponse_ERROR JoinResponse_Result = 1
)

// Enum value maps for JoinResponse_Result.
var (
	JoinResponse_Result_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	JoinResponse_Result_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x JoinResponse_Result) Enum() *JoinResponse_Result {
	p := new(JoinResponse_Result)
	*p = x
	return p
}

func (x JoinResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_meshservice_proto_enumTypes[0].Descriptor()
}

func (JoinResponse_Result) Type() protoreflect.EnumType {
	return &file_meshservice_proto_enumTypes[0]
}

func (x JoinResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinResponse_Result.Descriptor instead.
func (JoinResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{1, 0}
}

type JoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pubkey       string `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	EndpointIP   string `protobuf:"bytes,2,opt,name=endpointIP,proto3" json:"endpointIP,omitempty"`
	EndpointPort int32  `protobuf:"varint,3,opt,name=endpointPort,proto3" json:"endpointPort,omitempty"`
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *JoinRequest) GetEndpointIP() string {
	if x != nil {
		return x.EndpointIP
	}
	return ""
}

func (x *JoinRequest) GetEndpointPort() int32 {
	if x != nil {
		return x.EndpointPort
	}
	return 0
}

type JoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result       JoinResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=meshservice.JoinResponse_Result" json:"result,omitempty"`
	ErrorMessage string              `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Pubkey       string              `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	EndpointIP   string              `protobuf:"bytes,4,opt,name=endpointIP,proto3" json:"endpointIP,omitempty"`
	EndpointPort int32               `protobuf:"varint,5,opt,name=endpointPort,proto3" json:"endpointPort,omitempty"`
	JoinerMeshIP string              `protobuf:"bytes,6,opt,name=joinerMeshIP,proto3" json:"joinerMeshIP,omitempty"`
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetResult() JoinResponse_Result {
	if x != nil {
		return x.Result
	}
	return JoinResponse_OK
}

func (x *JoinResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JoinResponse) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *JoinResponse) GetEndpointIP() string {
	if x != nil {
		return x.EndpointIP
	}
	return ""
}

func (x *JoinResponse) GetEndpointPort() int32 {
	if x != nil {
		return x.EndpointPort
	}
	return 0
}

func (x *JoinResponse) GetJoinerMeshIP() string {
	if x != nil {
		return x.JoinerMeshIP
	}
	return ""
}

var File_meshservice_proto protoreflect.FileDescriptor

var file_meshservice_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x69, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x50, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x89, 0x02, 0x0a, 0x0c,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6d,
	0x65, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75,
	0x62, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b,
	0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x50,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x49, 0x50, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x6f,
	0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x68, 0x49, 0x50, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6a, 0x6f,
	0x69, 0x6e, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x68, 0x49, 0x50, 0x22, 0x1b, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x32, 0x4a, 0x0a, 0x04, 0x4d, 0x65, 0x73, 0x68, 0x12,
	0x42, 0x0a, 0x09, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x18, 0x2e, 0x6d,
	0x65, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x73, 0x63, 0x68, 0x6d, 0x69, 0x64, 0x74, 0x37, 0x35, 0x2f, 0x77, 0x67, 0x6d,
	0x65, 0x73, 0x68, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meshservice_proto_rawDescOnce sync.Once
	file_meshservice_proto_rawDescData = file_meshservice_proto_rawDesc
)

func file_meshservice_proto_rawDescGZIP() []byte {
	file_meshservice_proto_rawDescOnce.Do(func() {
		file_meshservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_meshservice_proto_rawDescData)
	})
	return file_meshservice_proto_rawDescData
}

var file_meshservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meshservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meshservice_proto_goTypes = []interface{}{
	(JoinResponse_Result)(0), // 0: meshservice.JoinResponse.Result
	(*JoinRequest)(nil),      // 1: meshservice.JoinRequest
	(*JoinResponse)(nil),     // 2: meshservice.JoinResponse
}
var file_meshservice_proto_depIdxs = []int32{
	0, // 0: meshservice.JoinResponse.result:type_name -> meshservice.JoinResponse.Result
	1, // 1: meshservice.Mesh.BeginJoin:input_type -> meshservice.JoinRequest
	2, // 2: meshservice.Mesh.BeginJoin:output_type -> meshservice.JoinResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meshservice_proto_init() }
func file_meshservice_proto_init() {
	if File_meshservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meshservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meshservice_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meshservice_proto_goTypes,
		DependencyIndexes: file_meshservice_proto_depIdxs,
		EnumInfos:         file_meshservice_proto_enumTypes,
		MessageInfos:      file_meshservice_proto_msgTypes,
	}.Build()
	File_meshservice_proto = out.File
	file_meshservice_proto_rawDesc = nil
	file_meshservice_proto_goTypes = nil
	file_meshservice_proto_depIdxs = nil
}
