// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: meshservice.proto

package meshservice

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type JoinResponse_Result int32

const (
	JoinResponse_OK    JoinResponse_Result = 0
	JoinResponse_ERROR JoinResponse_Result = 1
)

// Enum value maps for JoinResponse_Result.
var (
	JoinResponse_Result_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	JoinResponse_Result_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x JoinResponse_Result) Enum() *JoinResponse_Result {
	p := new(JoinResponse_Result)
	*p = x
	return p
}

func (x JoinResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_meshservice_proto_enumTypes[0].Descriptor()
}

func (JoinResponse_Result) Type() protoreflect.EnumType {
	return &file_meshservice_proto_enumTypes[0]
}

func (x JoinResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinResponse_Result.Descriptor instead.
func (JoinResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{2, 0}
}

type LeaveResponse_Result int32

const (
	LeaveResponse_OK    LeaveResponse_Result = 0
	LeaveResponse_ERROR LeaveResponse_Result = 1
)

// Enum value maps for LeaveResponse_Result.
var (
	LeaveResponse_Result_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	LeaveResponse_Result_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x LeaveResponse_Result) Enum() *LeaveResponse_Result {
	p := new(LeaveResponse_Result)
	*p = x
	return p
}

func (x LeaveResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaveResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_meshservice_proto_enumTypes[1].Descriptor()
}

func (LeaveResponse_Result) Type() protoreflect.EnumType {
	return &file_meshservice_proto_enumTypes[1]
}

func (x LeaveResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaveResponse_Result.Descriptor instead.
func (LeaveResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{4, 0}
}

type Peer_AnnouncementType int32

const (
	Peer_JOIN  Peer_AnnouncementType = 0
	Peer_LEAVE Peer_AnnouncementType = 1
)

// Enum value maps for Peer_AnnouncementType.
var (
	Peer_AnnouncementType_name = map[int32]string{
		0: "JOIN",
		1: "LEAVE",
	}
	Peer_AnnouncementType_value = map[string]int32{
		"JOIN":  0,
		"LEAVE": 1,
	}
)

func (x Peer_AnnouncementType) Enum() *Peer_AnnouncementType {
	p := new(Peer_AnnouncementType)
	*p = x
	return p
}

func (x Peer_AnnouncementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Peer_AnnouncementType) Descriptor() protoreflect.EnumDescriptor {
	return file_meshservice_proto_enumTypes[2].Descriptor()
}

func (Peer_AnnouncementType) Type() protoreflect.EnumType {
	return &file_meshservice_proto_enumTypes[2]
}

func (x Peer_AnnouncementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Peer_AnnouncementType.Descriptor instead.
func (Peer_AnnouncementType) EnumDescriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{5, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_meshservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{0}
}

type JoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// wireguard: public key of joiner node
	Pubkey string `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// wireguard: endpoint IP of joiner node
	EndpointIP string `protobuf:"bytes,2,opt,name=endpointIP,proto3" json:"endpointIP,omitempty"`
	// wireguard: endpoint UDP port of joiner node
	EndpointPort int32 `protobuf:"varint,3,opt,name=endpointPort,proto3" json:"endpointPort,omitempty"`
	// name of mesh to join
	MeshName string `protobuf:"bytes,4,opt,name=meshName,proto3" json:"meshName,omitempty"`
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRequest) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *JoinRequest) GetEndpointIP() string {
	if x != nil {
		return x.EndpointIP
	}
	return ""
}

func (x *JoinRequest) GetEndpointPort() int32 {
	if x != nil {
		return x.EndpointPort
	}
	return 0
}

func (x *JoinRequest) GetMeshName() string {
	if x != nil {
		return x.MeshName
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result       JoinResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=meshservice.JoinResponse_Result" json:"result,omitempty"`
	ErrorMessage string              `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	// this will be the joiner's mesh ip
	JoinerMeshIP string `protobuf:"bytes,3,opt,name=joinerMeshIP,proto3" json:"joinerMeshIP,omitempty"`
	// cidr of the mesh
	MeshCidr string `protobuf:"bytes,4,opt,name=meshCidr,proto3" json:"meshCidr,omitempty"`
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{2}
}

func (x *JoinResponse) GetResult() JoinResponse_Result {
	if x != nil {
		return x.Result
	}
	return JoinResponse_OK
}

func (x *JoinResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JoinResponse) GetJoinerMeshIP() string {
	if x != nil {
		return x.JoinerMeshIP
	}
	return ""
}

func (x *JoinResponse) GetMeshCidr() string {
	if x != nil {
		return x.MeshCidr
	}
	return ""
}

type LeaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pubkey string `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveRequest) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

type LeaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result       LeaveResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=meshservice.LeaveResponse_Result" json:"result,omitempty"`
	ErrorMessage string               `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveResponse) GetResult() LeaveResponse_Result {
	if x != nil {
		return x.Result
	}
	return LeaveResponse_OK
}

func (x *LeaveResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Peer contains connection data for an individual
// Wireguard Peer
type Peer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         Peer_AnnouncementType `protobuf:"varint,1,opt,name=type,proto3,enum=meshservice.Peer_AnnouncementType" json:"type,omitempty"`
	Pubkey       string                `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`              // public key
	EndpointIP   string                `protobuf:"bytes,3,opt,name=endpointIP,proto3" json:"endpointIP,omitempty"`      // endpoint
	EndpointPort int32                 `protobuf:"varint,4,opt,name=endpointPort,proto3" json:"endpointPort,omitempty"` // endpoint
	MeshIP       string                `protobuf:"bytes,5,opt,name=meshIP,proto3" json:"meshIP,omitempty"`              // internal mesh ip
}

func (x *Peer) Reset() {
	*x = Peer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_meshservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{5}
}

func (x *Peer) GetType() Peer_AnnouncementType {
	if x != nil {
		return x.Type
	}
	return Peer_JOIN
}

func (x *Peer) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *Peer) GetEndpointIP() string {
	if x != nil {
		return x.EndpointIP
	}
	return ""
}

func (x *Peer) GetEndpointPort() int32 {
	if x != nil {
		return x.EndpointPort
	}
	return 0
}

func (x *Peer) GetMeshIP() string {
	if x != nil {
		return x.MeshIP
	}
	return ""
}

type RTTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestedBy string `protobuf:"bytes,1,opt,name=requestedBy,proto3" json:"requestedBy,omitempty"` // node name
}

func (x *RTTRequest) Reset() {
	*x = RTTRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshservice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RTTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTTRequest) ProtoMessage() {}

func (x *RTTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshservice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTTRequest.ProtoReflect.Descriptor instead.
func (*RTTRequest) Descriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{6}
}

func (x *RTTRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type RTTResponseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node    string `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"` // node name
	RttMsec int32  `protobuf:"varint,2,opt,name=rttMsec,proto3" json:"rttMsec,omitempty"`
}

func (x *RTTResponseInfo) Reset() {
	*x = RTTResponseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshservice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RTTResponseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTTResponseInfo) ProtoMessage() {}

func (x *RTTResponseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meshservice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTTResponseInfo.ProtoReflect.Descriptor instead.
func (*RTTResponseInfo) Descriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{7}
}

func (x *RTTResponseInfo) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *RTTResponseInfo) GetRttMsec() int32 {
	if x != nil {
		return x.RttMsec
	}
	return 0
}

type RTTResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node string             `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"` // node name
	Rtts []*RTTResponseInfo `protobuf:"bytes,2,rep,name=rtts,proto3" json:"rtts,omitempty"`
}

func (x *RTTResponse) Reset() {
	*x = RTTResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshservice_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RTTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTTResponse) ProtoMessage() {}

func (x *RTTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshservice_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTTResponse.ProtoReflect.Descriptor instead.
func (*RTTResponse) Descriptor() ([]byte, []int) {
	return file_meshservice_proto_rawDescGZIP(), []int{8}
}

func (x *RTTResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *RTTResponse) GetRtts() []*RTTResponseInfo {
	if x != nil {
		return x.Rtts
	}
	return nil
}

var File_meshservice_proto protoreflect.FileDescriptor

var file_meshservice_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x85, 0x01, 0x0a, 0x0b, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x50, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49,
	0x50, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x6f, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x68, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x68, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0xc9, 0x01, 0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0c,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x68, 0x49, 0x50,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x68, 0x49, 0x50, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x68, 0x43, 0x69, 0x64, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x68, 0x43, 0x69, 0x64, 0x72,
	0x22, 0x1b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x22, 0x26, 0x0a,
	0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x01, 0x22, 0xdb, 0x01, 0x0a, 0x04, 0x50, 0x65, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6d, 0x65, 0x73,
	0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x2e, 0x41, 0x6e,
	0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a,
	0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x50, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x50, 0x12, 0x22, 0x0a, 0x0c,
	0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x73, 0x68, 0x49, 0x50, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x73, 0x68, 0x49, 0x50, 0x22, 0x27, 0x0a, 0x10, 0x41, 0x6e, 0x6e, 0x6f,
	0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x4a, 0x4f, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x10,
	0x01, 0x22, 0x2e, 0x0a, 0x0a, 0x52, 0x54, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x42, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x42,
	0x79, 0x22, 0x3f, 0x0a, 0x0f, 0x52, 0x54, 0x54, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x74, 0x74, 0x4d,
	0x73, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x74, 0x74, 0x4d, 0x73,
	0x65, 0x63, 0x22, 0x53, 0x0a, 0x0b, 0x52, 0x54, 0x54, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x72, 0x74, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x52, 0x54, 0x54, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x72, 0x74, 0x74, 0x73, 0x32, 0x79, 0x0a, 0x04, 0x4d, 0x65, 0x73, 0x68, 0x12,
	0x3d, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x32,
	0x0a, 0x05, 0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x6d, 0x65,
	0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x73, 0x63, 0x68, 0x6d, 0x69, 0x64, 0x74, 0x37, 0x35, 0x2f, 0x77, 0x67, 0x6d, 0x65,
	0x73, 0x68, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meshservice_proto_rawDescOnce sync.Once
	file_meshservice_proto_rawDescData = file_meshservice_proto_rawDesc
)

func file_meshservice_proto_rawDescGZIP() []byte {
	file_meshservice_proto_rawDescOnce.Do(func() {
		file_meshservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_meshservice_proto_rawDescData)
	})
	return file_meshservice_proto_rawDescData
}

var file_meshservice_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_meshservice_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_meshservice_proto_goTypes = []interface{}{
	(JoinResponse_Result)(0),   // 0: meshservice.JoinResponse.Result
	(LeaveResponse_Result)(0),  // 1: meshservice.LeaveResponse.Result
	(Peer_AnnouncementType)(0), // 2: meshservice.Peer.AnnouncementType
	(*Empty)(nil),              // 3: meshservice.Empty
	(*JoinRequest)(nil),        // 4: meshservice.JoinRequest
	(*JoinResponse)(nil),       // 5: meshservice.JoinResponse
	(*LeaveRequest)(nil),       // 6: meshservice.LeaveRequest
	(*LeaveResponse)(nil),      // 7: meshservice.LeaveResponse
	(*Peer)(nil),               // 8: meshservice.Peer
	(*RTTRequest)(nil),         // 9: meshservice.RTTRequest
	(*RTTResponseInfo)(nil),    // 10: meshservice.RTTResponseInfo
	(*RTTResponse)(nil),        // 11: meshservice.RTTResponse
}
var file_meshservice_proto_depIdxs = []int32{
	0,  // 0: meshservice.JoinResponse.result:type_name -> meshservice.JoinResponse.Result
	1,  // 1: meshservice.LeaveResponse.result:type_name -> meshservice.LeaveResponse.Result
	2,  // 2: meshservice.Peer.type:type_name -> meshservice.Peer.AnnouncementType
	10, // 3: meshservice.RTTResponse.rtts:type_name -> meshservice.RTTResponseInfo
	4,  // 4: meshservice.Mesh.Join:input_type -> meshservice.JoinRequest
	3,  // 5: meshservice.Mesh.Peers:input_type -> meshservice.Empty
	5,  // 6: meshservice.Mesh.Join:output_type -> meshservice.JoinResponse
	8,  // 7: meshservice.Mesh.Peers:output_type -> meshservice.Peer
	6,  // [6:8] is the sub-list for method output_type
	4,  // [4:6] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_meshservice_proto_init() }
func file_meshservice_proto_init() {
	if File_meshservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meshservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshservice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RTTRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshservice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RTTResponseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshservice_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RTTResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meshservice_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meshservice_proto_goTypes,
		DependencyIndexes: file_meshservice_proto_depIdxs,
		EnumInfos:         file_meshservice_proto_enumTypes,
		MessageInfos:      file_meshservice_proto_msgTypes,
	}.Build()
	File_meshservice_proto = out.File
	file_meshservice_proto_rawDesc = nil
	file_meshservice_proto_goTypes = nil
	file_meshservice_proto_depIdxs = nil
}
